project:
  type: website
  output-dir: docs
website:
  title: "Forgeurs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: "Nous découvrir"
    right:
      - icon: instagram
        href: https://www.instagram.com/les_forgeurs_daventures_jdr/
        aria-label: Instagram
      - icon: facebook
        href: https://www.facebook.com/jdrlaforge/?locale=fr_FR
        aria-label: Facebook
      - icon: envelope
        href: mailto:lesforgeursdaventures@gmail.com
        aria-label: Email
      - icon: agenda
        href: https://www.eventbrite.fr/o/les-forgeurs-daventures-nantes-72524511583

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true

linkcolor: "#7ec0efff"



