project:
  type: website
  output-dir: docs
website:
  title: "Les Forgeurs d'Aventures"
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
        
      - text: "Les MJ"
        href: pages/les_mj.qmd

      - text: "Le Jeu de Rôle"
        menu:
        - text: "Les univers"
          href: pages/jdr/univers.qmd
        - text: "Les systèmes de jeu"
          href: pages/jdr/systemes.qmd

      - text: "L'association"
        menu:
        - text: "Nous découvrir"
          href: pages/lassociation/decouvrir.qmd
        - text: "Galerie"
          href: pages/lassociation/galerie.qmd
        - text: "Nos partenaires"
          href: pages/lassociation/partenaires.qmd
        - text: "Nous soutenir"
          href: pages/lassociation/nous_soutenir.qmd

      - text: "Inscriptions"
        href: https://www.eventbrite.fr/o/les-forgeurs-daventures-nantes-72524511583

      
    right:
      - icon: instagram
        href: https://www.instagram.com/les_forgeurs_daventures_jdr/
        aria-label: Instagram
      - icon: facebook
        href: https://www.facebook.com/jdrlaforge/?locale=fr_FR
        aria-label: Facebook
      - icon: discord
        href: https://discord.gg/dJEZbR4ZGJ
        aria-label: Discord
      - icon: envelope
        href: mailto:lesforgeursdaventures@gmail.com
        aria-label: Email

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true

linkcolor: "#7ec0efff"

margin-header: |
  ![](/images/logo_t.png)

filters:
  - timeline