project:
  type: website
  output-dir: docs
website:
  title: "Forgeurs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: "Nous découvrir"
      - href: pages/contact.qmd
        text: Contact
      - href: https://www.eventbrite.fr/o/les-forgeurs-daventures-nantes-72524511583
        text: Sessions

format:
  html:
    theme:
      - superhero
    css: styles.css
    toc: true

linkcolor: "#7ec0efff"



