---
title: "Félix"
description: "Le dernier arrivé"
---


## Les univers

### Star Wars (1987)

Basé sur la saga culte, cette version de *Star Wars* utilise le système D6, très adapté aux débutants. Le système est permissif et va naturellement provoquer des scènes rocambolesques, des situations improbables, des retournements de situation inattendus... De quoi se créer facilement de bons souvenirs. 

Le jeu est très tourné sur l'aventure et l'action, mais attention : ici vous n'incarnerez ni Jedi ni Sith, vous serez bien souvent un simple rebelle ou un pirate de l'espace essayant de survivre dans la Galaxie lointaine, très lointaine.

Les scénarios peuvent prendre place à différentes époques du film, mais se font souvent entre l'épisode 3 et 4, lorsque l'Empire est à son apogée et que les rebelles sont encore très faibles.

Batailles épiques, infiltrations ratées et fuites à toute vitesse sont au programme !

::: {.callout-note}
## Le système D6
Votre personnage possède des compétences, comme "Combat au corps à corps" ou "Pilotage", dont la valeur est représentée par un nombre de dés (exemple : 3D).
Lorsque vous voulez faire une action, vous lancez un nombre de dés égal à votre compétence. La difficulté dépend de l'action et de la situation, et fonctionne par seuils : 5 = facile, 10 = moyen, 15 = difficile, etc.
Ainsi, vous pouvez rapidement devenir très bon dans une compétence, mais aussi très mauvais. C'est un système simple et efficace, qui permet de se concentrer sur l'histoire plutôt que sur les règles.
:::

Quelques scénarios que je fais jouer fréquemment :

- *Le Casino de Canto Bight* : Vous jouez un groupe de pirates n'ayant plus beaucoup de crédits en poche. La bonne nouvelle, c'est que le casino de Canto Bight organise prochainement son grand tournoi de Sabacc, avec une récompense de 100.000 crédits pour le gagnant ! La mauvaise, c'est que vous n'avez pas les moyens de payer les frais d'inscription, et vous allez devoir trouver un moyen de participer à ce tournoi.

- *Le temple des Terres Sauvages* : Vous jouez un groupe de rebelles luttant contre l'Empire. Récemment, vos informateurs ont intercepté une communication des impériaux indiquant qu'ils mènent des recherches sur un temple ancien situé dans les Terres Sauvages, ce qui est particulièrement inquiétant puisque cette région de la Galaxie n'a jamais été explorée et encore moins civilisée. Vous feriez mieux de vous y rendre pour savoir ce qui s'y passe, et surtout pour empêcher les impériaux de mettre la main sur ce qui se trouve dans le temple.

- *En territoire ennemi* : Vous jouez un groupe de rebelles luttant contre l'Empire. Vous venez de ramener à la base un disque de données contenant des informations importantes sur les plans de l'Empire. Malheureusement, vous ne disposez pas d'un appareil suffisamment puissant pour casser le cryptage. *L'Empire, en revanche...* Vous allez devoir monter à bord d'un Destroyer Impérial en vous faisant passer pour des stormtroopers, puis trouver un moyen de récupérer les données avant que l'Empire ne s'en rende compte.


### Avatar Legends
Basé sur le manga et les séries animées *Avatar, le dernier maître de l'air* et *La légende de Korra*, le jeu utilise le système *PbA* (Powered by the Apocalypse / Propulsé par l'apocalypse). Les joueurs se retrouvent dans des zones sinistrées à devoir aider les survivants, combattre des bandits, faire face à des catastrophes naturelles... 
Ce système de jeu est beaucoup moins axé sur le combat et la stratégie, et plus sur la narration et les interactions entre les personnages. C'est un système de jeu plus exigeant, mais qui permet de créer des histoires plus profondes et plus immersives. Ici, foncer dans le tas est rarement une bonne idée et il vous faudra comprendre les rapports de force entre les factions avant d'agir.

Les scénarios peuvent prendre place à toutes les époques de la série, de Kyoshi à Korra.

::: {.callout-note}
## Le système PbA
Ce système se joue avec deux dés à six faces (2D6). Moins de 7 : c'est un échec. Entre 7 et 9 : c'est un succès partiel, avec un coût ou une complication. 10 ou plus : c'est un succès total. Le *PbA* repose sur des "mouvements" ou "actions", que les joueurs peuvent effectuer. Par exemple, dans *Avatar Legends*, si vous souhaitez distraire un ennemi : que vous utilisiez la maîtrise d'un élément, que vous lanciez un caillou ou que vous usiez de votre charme, vous utilisez l'action "*Tromper l'ennemi*".

Les jeux utilisant le système PbA sont souvent plus narratifs et moins axés sur les règles que les jeux traditionnels. Ils mettent l'accent sur les choix des joueurs et les conséquences de leurs actions, plutôt que sur la gestion de leurs statistiques ou de leur équipement.
:::

Quelques scénarios que je fais jouer fréquemment :

- *Les Pirates des Iles Carmin* : L'avatar Aang vient de battre le Seigneur du Feu Ozai et commence la reconstruction du Royaume de la Terre avec l'aide du nouveau seigneur du feu Zuko. Malheureusement une bande de pirates, qui était relativement calme depuis des années, a pillé une cargaison destinée à la reconstruction du Royaume de la Terre. Sans elle, le Royaume risque de ne pas croire à la nouvelle ère de paix et de prospérité, et pourrait même se tourner vers des solutions plus radicales pour se dédommager des dégâts causés par la Nation du Feu. Vous êtes envoyés pour retrouver les pirates et récupérer la cargaison.

- *La mèche brûle* : Après le siège de la Cité de la République par Kuvira, la ville retrouve son calme et tout le monde travaille à sa reconstruction. Juniper Kim, ancienne scientifique au service du Royaume de la Terre, essaye de se racheter en trouvant des applications pacifistes aux armes développées pour le siège : elle étudie notamment l'encapsulation de l'énergie spirituelle dans des bonbonnes. Ce qu'elle ignorait, c'est qu'il existe de nombreuses factions intéressées par ses recherches, et l'une d'elle vient de voler plusieurs bonbonnes. Vous êtes envoyés pour les récupérer, mais vous allez vite découvrir que les bonbonnes sont plus dangereuses que ce que vous pensiez, et que les factions intéressées par ces recherches sont prêtes à tout pour les obtenir.


## A propos de moi

Après avoir découvert le Jeu de Rôle au lycée, c'est la découverte de Baldur's Gate 3 en 2023, qui m'a donné envie de reprendre le jeu sur table. Après un an comme joueur à la table de [Bernard](pages/les_mj/bernard.qmd), je me suis lancé comme MJ à mon tour.